### ISSUE TITLE
Math-Magicians: Hooks

### ISSUE THREAD

**Issue by kkolade** [kkolade/math-magicians#4]
The Math-Magicians application so far has been implemented using functional components thus no state property is defined as comes typically with the class-based component.
Therefore to implement state and manage the state, React hook useState was implemented.
React hooks are actually functions provided by React that are used to 'hook into' React state and lifecycle features in functional components.

The specific React hook used in this application is useState, this is used to add state to a functional component.
The useState is a function that accepts the state variable as an argument and returns an array containing the same state variable and a state modifier (a function that can be used to modify the state variable)
To have access to the useState hook, it must first be imported from React.

In this application, the useState is used in the Calculator.jsx component, it is passed a variable state of {0} and its return values is destructured into 'state variable' : result and 'state modifier': setResult which is then used in the handleClick function to manage the result displayed by the calculator

**Comment by huseyinbiyik** [comment]
Hi @kkolade,

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
